---
# tasks file for ansible-do
- name: Create a new DO droplet
  digital_ocean_droplet:
    state: present
    name: testserver
    size: 1gb
    region: nyc3
    image: ubuntu-18-04-x64
    wait_timeout: 500
  register: testdroplet

- name: Ensure the new droplet is present
  digital_ocean_droplet:
    state: present
    name: {{ testdroplet.droplet.name }}
    size: {{ testdroplet.droplet.size }}
    region: {{ testdroplet.droplet.region }}
    image: {{ testdroplet.droplet.image }}
    wait_timeout: 500

- name: Set DNS records
  digital_ocean_domain:
    state: present
    name: "{{ testdroplet.droplet.name }}.miller.com"
    ip: {{ testdroplet.droplet.ip_address }}