# Wyatt's first ansible playbook
# Written by Wyatt J. Miller, 2019
#
# Installing/setting up all the things for a Wordpress instance
# note that the ppa doesn't work so the script is a bit broken \o/
# Instead I just creating one web server

- hosts: all
  become: true
  tasks:
    - name: "Pinging all the things"
      ping:
    - name: "PPA time!"
      apt_repository: repo=ppa:ondrej/php
    - name: "Update APT cache"
      apt: update_cache=yes cache_valid_time=3600
    
    # Installing PHP via the PPA 
    - name: "Installing PHP"
      apt: 
        name: ['php5', 'php5-fpm', 'php5-mysql'] 
        state: present
    
    # We don't want apache
    - name: "Removing apache"
      apt: name=apache2 state=removed
      
    # Installing and configuring MySQL
    - name: "Installing MySQL and a MySQL client library"
      apt: name={{ item }} state=installed
      with_items:
        - mysql-server-5.6
        - python-mysqldb
    - name: "Generating mysql password"
      command: openssl rad -hex 7 creates=/root/.my.cnf
      register: mysql_new_root_pass
    - name: "Remove needless users"
      mysql_user: name="" state=absent
      when: mysql_new_root_pass.changed
    - name: "Remove test database"
      mysql_db: name=test state=absent
      when: mysql_new_root_pass.changed
    - name: "Setting mysql root password"
      mysql_user: name=root login_host={{ item }} login_password={{ mysql_new_root_pass.stdout }}
      with_items:
        - localhost
        - 127.0.0.1
      when: mysql_new_root_pass.changed
    - name: "Output mysql password"
      debug: msg="New mysql root password is {{ mysql_new_root_pass.stdout }}"
    - name: "Create my.cnf"
      template: src="templates/my.cnf" dest="/root/.my.cnf"
      when: mysql_new_root_pass.changed

    # Installing and configuring nginx
    - name: "Installing nginx"
      apt: name=nginx state=installed
    - name: "Starting the nginx service"
      service: name=nginx state=started
    - name: "Create nginx config file"
      template: src="templates/default" dest="/etc/nginx/sites-available/default"
  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
    - name: Create nginx config file
      template:
        src: "templates/default"
        dest: "/etc/nginx/sites-available/default"
