# Docker script written in Ansible
# Written by Wyatt J. Miller, 2019
#
# Spins up Docker containers with this one playbook

- hosts: localhost

  tasks:
    - name: "Create a Docker data container"
      docker_container:
        name: data01
        image: busybox
        state: started
        command: ["sleep", "infinity"]
        volumes:
          - /data/busybox
    
    - name: "Create a Docker NoSQL container"
      docker_container:
        name: mongo01
        image: mongo
        ports:
          - "27017:27017"
        state: started
        volumes:
          - /data/mongo

    - name: "Create a Cassandra container"
      docker_container:
        name: cassandra01
        image: cassandra
        state: started
        ports:
          - "7199:7199"
          - "7000:7000"
          - "7001:7001"
          - "9160:9160"
          - "9042:9042"
        networks:
          - name: "bridge"
        volumes:
          - /data/cassandra