# Cron script in Ansible
# Written by Wyatt J. Miller, 2019
#
# A cron script that'll create a cron job and delete the same cron job

- hosts: localhost

  tasks:
  - name: "Create a cron job"
    cron:
      name: "Backup my backups"
      hour: "0"
      minute: "0"
      job: "tar cvzf backup.tar.gz *.tar.gz > /dev/null"

  - name: "Delete previous cron job"
    cron:
      name: "Backup my backups"
      state: absent
